variables:
  BUILD_IMAGES_PROJECT: openconnect/build-images
  CENTOS6_BUILD: openconnect-cli-centos6
  CENTOS7_BUILD: openconnect-cli-centos7
  CENTOS8_BUILD: openconnect-cli-centos8
  FEDORA_BUILD: openconnect-cli-fedora
  UBUNTU_BUILD: openconnect-cli-ubuntu 

image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$FEDORA_BUILD

CentOS7/GnuTLS:
  image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$CENTOS7_BUILD
  script:
  - ./autogen.sh
  - ./configure --with-java CFLAGS=-g
  - make -j4
# UTF-8 support is not available
  - make VERBOSE=1 XFAIL_TESTS="auth-nonascii" -j4 check
  tags:
  - shared
  except:
  - tags
  - schedules
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - tests/*.log

CentOS7/OpenSSL:
  image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$CENTOS7_BUILD
  script:
  - ./autogen.sh
  - ./configure --without-gnutls --with-openssl --with-java --without-openssl-version-check --enable-dtls-xfail --disable-dsa-tests CFLAGS=-g
  - make -j4
# UTF-8 support is not available
  - make VERBOSE=1 XFAIL_TESTS="auth-nonascii" -j4 check
  tags:
  - shared
  except:
  - tags
  - schedules
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - tests/*.log

CentOS8/GnuTLS:
  image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$CENTOS8_BUILD
  script:
  - ./autogen.sh
  - ./configure --with-java --without-gnutls-version-check --disable-dsa-tests CFLAGS=-g
  - make -j4
# UTF-8 support is not available
  - make VERBOSE=1 XFAIL_TESTS="auth-nonascii" -j4 check
  tags:
  - shared
  except:
  - tags
  - schedules
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - tests/*.log

CentOS8/OpenSSL:
  image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$CENTOS8_BUILD
  script:
  - ./autogen.sh
  - ./configure --without-gnutls --with-openssl --with-java --without-openssl-version-check --disable-dsa-tests CFLAGS=-g
  - make -j4
# UTF-8 support is not available
# OpenSSL 1.1.0 disables 3DES and RC4 by default (https://www.openssl.org/blog/blog/2016/08/24/sweet32/)
  - make VERBOSE=1 XFAIL_TESTS="auth-nonascii obsolete-server-crypto" -j4 check
  tags:
  - shared
  except:
  - tags
  - schedules
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - tests/*.log

CentOS6/OpenSSL:
  image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$CENTOS6_BUILD
  script:
  - ./autogen.sh
  - ./configure --with-java --without-openssl-version-check --enable-dtls-xfail CFLAGS=-g
  - make -j4
# UTF-8 support is not available
  - make VERBOSE=1 XFAIL_TESTS="bad_dtls_test auth-nonascii" -j4 check
  tags:
  - shared
  except:
  - tags
  - schedules
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - tests/*.log

Signoff:
  script:
  # Quoted to work around https://gitlab.com/gitlab-org/gitlab-foss/-/issues/20177
  - 'echo "Checking for new commits without Signed-off-by: tags as described in http://www.infradead.org/openconnect/contribute.html"'
  # Last bad commit
  - 'git log ceab1765db11c15a18a0c605812dbc11afd63e8b.. --grep "(^Signed-off-by)|(^Merge branch)|(^This reverts commit)" --extended-regexp --invert-grep --exit-code'
  - echo "None (good)"

Coverity:
  image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$CENTOS8_BUILD
  only:
  - schedules
  - coverity
  script:
  - curl -o /tmp/cov-analysis-linux64.tgz https://scan.coverity.com/download/linux64
    --form project=$COVERITY_SCAN_PROJECT_NAME --form token=$COVERITY_SCAN_TOKEN
  - tar xfz /tmp/cov-analysis-linux64.tgz
  - ./autogen.sh
  - ./configure --with-java --without-gnutls --with-openssl --disable-dsa-tests
  - cd java
  - ../cov-analysis-linux64-*/bin/cov-build --dir ../cov-int ant
  - cd ..
  - cov-analysis-linux64-*/bin/cov-build --dir cov-int make -j4
  - make clean
  - ./configure --with-java --disable-dsa-tests --without-gnutls-version-check
  - cov-analysis-linux64-*/bin/cov-build --dir cov-int make -j4
  - tar cfz cov-int.tar.gz cov-int
  - curl https://scan.coverity.com/builds?project=$COVERITY_SCAN_PROJECT_NAME
    --form token=$COVERITY_SCAN_TOKEN --form email=email=$GITLAB_USER_EMAIL
    --form file=@cov-int.tar.gz --form version="`git describe --tags`"
    --form description="`git describe --tags` / $CI_COMMIT_TITLE / $CI_COMMIT_REF_NAME:$CI_PIPELINE_ID "
  tags:
  - shared
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - cov-int/*.txt

Fedora/GnuTLS:
  script:
  - ./autogen.sh
  - ./configure --with-java --disable-dsa-tests --without-gnutls-version-check CFLAGS=-g
  - make tmp-distdir
  - cd openconnect-$(git describe --tags | sed s/^v//)
  - ./configure --with-java --disable-dsa-tests --without-gnutls-version-check CFLAGS=-g
  - make -j4
  # Disable rdrand to work around https://bugzilla.redhat.com/1831086
  - make VERBOSE=1 OPENSSL_ia32cap=~0x4000000000000000 -j4 check
  tags:
  - shared
  except:
  - tags
  - schedules
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - tests/*.log

Fedora/GnuTLS/clang:
  script:
  - ./autogen.sh
  - ./configure --with-java --disable-dsa-tests --without-gnutls-version-check CC=clang CFLAGS=-g
  - make tmp-distdir
  - cd openconnect-$(git describe --tags | sed s/^v//)
  - ./configure --with-java --disable-dsa-tests --without-gnutls-version-check CC=clang CFLAGS=-g
  - make -j4
  # Disable rdrand to work around https://bugzilla.redhat.com/1831086
  - make VERBOSE=1 OPENSSL_ia32cap=~0x4000000000000000 -j4 check
  tags:
  - shared
  except:
  - tags
  - schedules
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - tests/*.log

Fedora/OpenSSL:
  script:
# Re-enable DSA since we test it
  - update-crypto-policies --set LEGACY
  - ./autogen.sh
  - ./configure --without-gnutls --with-openssl --without-openssl-version-check --disable-dsa-tests CFLAGS=-g
  - make tmp-distdir
  - cd openconnect-$(git describe --tags | sed s/^v//)
  - ./configure --without-gnutls --with-openssl --without-openssl-version-check --disable-dsa-tests CFLAGS=-g
  - make -j4
# OpenSSL 1.1.0 disables 3DES and RC4 by default (https://www.openssl.org/blog/blog/2016/08/24/sweet32/)
  - make VERBOSE=1 XFAIL_TESTS="obsolete-server-crypto" -j4 check
  tags:
  - shared
  except:
  - tags
  - schedules
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - tests/*.log

Fedora/OpenSSL/clang:
  script:
# Re-enable DSA since we test it
  - update-crypto-policies --set LEGACY
  - ./autogen.sh
  - ./configure CC=clang --without-gnutls --with-openssl --without-openssl-version-check --disable-dsa-tests CFLAGS=-g
  - make tmp-distdir
  - cd openconnect-$(git describe --tags | sed s/^v//)
  - ./configure CC=clang --without-gnutls --with-openssl --without-openssl-version-check --disable-dsa-tests CFLAGS=-g
  - make -j4
# OpenSSL 1.1.0 disables 3DES and RC4 by default (https://www.openssl.org/blog/blog/2016/08/24/sweet32/)
  - make VERBOSE=1 XFAIL_TESTS="obsolete-server-crypto" -j4 check
  tags:
  - shared
  except:
  - tags
  - schedules
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - tests/*.log

Ubuntu18.04/GnuTLS:
  image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$UBUNTU_BUILD
  script:
  - ./autogen.sh
  - ./configure --with-java CFLAGS=-g
  - make -j4
# UTF-8 support is not available
  - make VERBOSE=1 XFAIL_TESTS="auth-nonascii" -j4 check
  tags:
  - shared
  except:
  - tags
  - schedules
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - tests/*.log

Ubuntu18.04/OpenSSL:
  image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$UBUNTU_BUILD
  script:
  - ./autogen.sh
  - ./configure --without-gnutls --with-openssl --with-java --without-openssl-version-check --disable-dsa-tests CFLAGS=-g
  - make -j4
# UTF-8 support is not available
# OpenSSL 1.1.0 disables 3DES and RC4 by default (https://www.openssl.org/blog/blog/2016/08/24/sweet32/)
  - make VERBOSE=1 XFAIL_TESTS="auth-nonascii obsolete-server-crypto" -j4 check
  tags:
  - shared
  except:
  - tags
  - schedules
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - tests/*.log

MinGW32/GnuTLS:
  script:
  - mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc
  - echo ':DOSWin:M::MZ::/usr/bin/wine:' > /proc/sys/fs/binfmt_misc/register
  - ./autogen.sh
  - mingw32-configure --without-gnutls-version-check CFLAGS=-g
  - make -j4
# These tests seem to fail due to wine failing to start; setting as XFAIL
# since these never run before this patch set.
  - make VERBOSE=1 -j4 check XFAIL_TESTS="sigterm dtls-psk"
  tags:
  - shared
  except:
  - tags
  - schedules
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - tests/*.log

MinGW32/OpenSSL:
  script:
  - mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc
  - echo ':DOSWin:M::MZ::/usr/bin/wine:' > /proc/sys/fs/binfmt_misc/register
  - ./autogen.sh
  - mingw32-configure --without-gnutls --with-openssl --without-openssl-version-check CFLAGS=-g
  - make -j4
# These tests seem to fail due to wine failing to start; setting as XFAIL
# since these never run before this patch set.
  - make VERBOSE=1 -j4 check XFAIL_TESTS="sigterm dtls-psk"
  tags:
  - shared
  except:
  - tags
  - schedules
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - tests/*.log

MinGW64/GnuTLS:
  script:
  - dnf remove -y wine.i686
  - mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc
  - echo ':DOSWin:M::MZ::/usr/bin/wine:' > /proc/sys/fs/binfmt_misc/register
  - ./autogen.sh
  - mingw64-configure --without-gnutls-version-check CFLAGS=-g
  - make -j4
# These tests seem to fail due to wine failing to start; setting as XFAIL
# since these never run before this patch set.
  - make VERBOSE=1 -j4 check XFAIL_TESTS="sigterm dtls-psk"
  tags:
  - shared
  except:
  - tags
  - schedules
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - tests/*.log

MinGW64/OpenSSL:
  script:
  - dnf remove -y wine.i686
  - mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc
  - echo ':DOSWin:M::MZ::/usr/bin/wine:' > /proc/sys/fs/binfmt_misc/register
  - ./autogen.sh
  - mingw64-configure --without-gnutls --with-openssl --without-openssl-version-check CFLAGS=-g
  - make -j4
# These tests seem to fail due to wine failing to start; setting as XFAIL
# since these never run before this patch set.
  - make VERBOSE=1 -j4 check XFAIL_TESTS="sigterm dtls-psk"
  tags:
  - shared
  except:
  - tags
  - schedules
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - tests/*.log
